# Generated by Django 3.2.5 on 2021-07-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('by_end_date', models.DateField()),
                ('meeting_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
