version: "3"

services:
  backend:
    image: ghcr.io/cliqteam/when2meet-backend:dev
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile

    command: /dev.sh
    depends_on:
      - postgres

    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      - SQL_USER=compose
      - SQL_PASSWORD=compose
      - SQL_DATABASE=when2meet
      - SQL_HOST=postgres
      - SQL_PORT=5432

  frontend:
    image: ghcr.io/cliqteam/when2meet-frontend:dev
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile.dev

    tty: true

    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8080:8080

  postgres:
    image: postgres:12.3-alpine

    logging:
      driver: none

    environment:
      - POSTGRES_USER=compose
      - POSTGRES_PASSWORD=compose
      - POSTGRES_DB=when2meet
