version: "3"

services:
  django:
    image: cliqteam/django:dev
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile

    command: /dev.sh
    depends_on:
      - postgres

    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    environment:
      - SQL_DATABASE=djangotemplate
      - SQL_USER=djangotemplate
      - SQL_PASSWORD=djangotemplate
      - SQL_HOST=postgres
      - SQL_PORT=5432
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    env_file:
      - .env

  vue:
    image: cliqteam/vue:dev
    build:
      context: .
      dockerfile: ./docker/vue/Dockerfile

    tty: true

    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8080:8080

  postgres:
    image: postgres:12.3-alpine

    logging:
      driver: none

    environment:
      - POSTGRES_USER=djangotemplate
      - POSTGRES_PASSWORD=djangotemplate
      - POSTGRES_DB=djangotemplate
