version: "3"

services:
  backend:
    image: ghcr.io/cliqteam/when2meet-backend:dev
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile

    restart: unless-stopped
    command: /dev.sh
    depends_on:
      - postgres

    volumes:
      - ./backend:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      - SQL_USER=compose
      - SQL_PASSWORD=compose
      - SQL_DATABASE=when2meet
      - SQL_HOST=postgres
      - SQL_PORT=5432

  frontend:
    image: ghcr.io/cliqteam/when2meet-frontend:dev
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile.dev

    restart: unless-stopped
    tty: true

    volumes:
      - ./frontend:/app
      - /app/node_modules

  ingress:
    image: nginx

    restart: unless-stopped
    logging:
      driver: none
    depends_on:
      - backend
      - frontend

    volumes:
      - ./docker/ingress/conf:/etc/nginx/conf.d:ro
    ports:
      - 8080:80

  postgres:
    image: postgres:12.3-alpine

    restart: unless-stopped
    logging:
      driver: none

    environment:
      - POSTGRES_USER=compose
      - POSTGRES_PASSWORD=compose
      - POSTGRES_DB=when2meet
