FROM node:lts-alpine as build-stage

WORKDIR /app

COPY --chown=node:node ./frontend/package*.json ./

RUN npm install &&\
    npm install @vue/cli

COPY --chown=node:node ./frontend ./

RUN npm run build

FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html

COPY ./docker/frontend/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
