FROM node:lts-alpine

ENV NODE_ENV=development

RUN apk add --no-cache tini

COPY ./docker/frontend/*.sh /
RUN chmod +x /*.sh

EXPOSE 8080
VOLUME ["/app"]
WORKDIR /app

# Entrypoint logic
ENTRYPOINT ["/sbin/tini", "--", "/entrypoint.sh"]
