FROM node:lts-alpine

ENV NODE_ENV=development

WORKDIR /app

COPY --chown=node:node ./frontend/package*.json ./

RUN npm install &&\
    npm install @vue/cli

EXPOSE 8080
VOLUME ["/app"]

CMD ["npm", "run", "serve"]
