name: deploy-staging

on:
  workflow_run:
    workflows: ["backend", "frontend"]
    branches: [master]
    types:
      - completed
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  DEPLOY_SERVER: when2meet.cliqteam.com
  DEPLOY_USER: when2meet-staging
  DEPLOY_ROOT: /srv/when2meet-staging
  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY_STAGING }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      packages: read

    steps:
      - name: Pull images and start services on remote server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            cd ${{ env.DEPLOY_ROOT }}
            docker-compose down
            docker-compose pull
            docker-compose up -d || exit 1
          host: ${{ env.DEPLOY_SERVER }}
          username: ${{ env.DEPLOY_USER }}
          privateKey: ${{ env.DEPLOY_KEY }}
