name: Deploy to Staging

on:
  push:
    branches:
      - staging

env:
  COMPOSE_FILE: "/srv/when2meet/compose/docker-compose.yaml"

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: read

    steps:
      - name: Pull images and start services on staging server
        uses: garygrossgarten/github-action-ssh@release
        with:
          # TODO: Add step that verifies that docker-compose up was a success
          command: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker-compose -f /srv/when2meet/compose/docker-compose.yaml up -d
          host: ${{ secrets.STAGING_SERVER }}
          username: root
          privateKey: ${{ secrets.DEPLOY_KEY_STAGING }}
