name: Deploy to Staging

on:
  push:
    branches:
      - staging

env:
  STAGING_SERVER: "104.131.35.188"
  COMPOSE_FILE: "/srv/when2meet/compose/docker-compose.yaml"

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: read

    steps:
      - name: Pull images and start services on staging server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker-compose up -f /srv/when2meet/compose/docker-compose.yaml -d
          host: ${{ env.STAGING_SERVER }}
          username: root
          privateKey: ${{ secrets.DEPLOY_KEY_STAGING }}
