name: frontend

on:
  push:
    paths:
      - docker/frontend/**
      - frontend/**
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cliqteam/when2meet-frontend
  IMAGE_DOCKERFILE: docker/frontend/Dockerfile.prod
  COMPOSE_FILE: docker-compose.yaml

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker images
        run: docker-compose build frontend

      - name: Run linting
        run: |
          docker-compose run \
            --rm \
            frontend npm run lint

      - name: Run build test
        run: |
          docker-compose run \
            --rm \
            frontend npm run build

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          file: ${{ env.IMAGE_DOCKERFILE }}
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
