name: Frontend Workflow (Vue Web Interface)

on:
  push:
    paths:
      - docker/frontend/**
      - frontend/**
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  COMPOSE_FILE: docker-compose.yaml

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker images
        run: docker-compose build frontend

      - name: Run linting
        run: |
          docker-compose run \
            --rm \
            frontend npm run lint

      - name: Run build test
        run: |
          docker-compose run \
            --rm \
            frontend npm run build
