name: Test backend code

on:
  push:
    paths:
      - docker/backend/**
      - backend/**

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 3.7, 3.8, 3.9
        python-version: [3.6]

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: cliqteam/when2meet-backend
      COMPOSE_FILE: docker-compose.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker images
        run: docker-compose build backend

      - name: Run tests
        run: |
          docker-compose run \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            -e RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }} \
            -e RECAPTCHA_SITE_KEY=${{ secrets.RECAPTCHA_SITE_KEY }} \
            backend /test.sh
